### ISSUE TITLE
Dimension size must be evenly divisible by N but is M for 'loss/Reshape_1'

### ISSUE THREAD

**Issue by gccome** [dmis-lab/biobert#12]
Hello, I am trying to use BioBERT to fine tune i2b2-2010 dataset which has three entities to be extracted: treatment, test, and problem. The only code I changed in run_ner.py is `get_labels` function in class NerProcessor. I changed it to below: 
```
def get_labels(self):
    return ["O", "X", "[CLS]", "[SEP]", "B-test", "I-test", "B-problem", "I-problem", "B-treatment", "I-treatment"]
```
I also changed training batch size to 16 due to my GPU memory.
However, when I run run_ner.py, I got the following error:
```
Traceback (most recent call last):
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension size must be evenly divisible by 896 but is 22528 for 'loss/Reshape_1' (op: 'Reshape') with input shapes: [2048,11], [3] and with input tensors computed as partial shapes: input[1] = [?,128,7].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_ner.py", line 630, in <module>
    tf.app.run()
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_ner.py", line 555, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2409, in train
    rendezvous.raise_errors()
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2403, in train
    saving_listeners=saving_listeners
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn
    features, labels, mode, config)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2479, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1259, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1533, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "run_ner.py", line 412, in model_fn
    num_labels, use_one_hot_embeddings)
  File "run_ner.py", line 382, in create_model
    logits = tf.reshape(logits, [-1, FLAGS.max_seq_length, 7])
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6482, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/home/daniel/PycharmProjects/biobert/.venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension size must be evenly divisible by 896 but is 22528 for 'loss/Reshape_1' (op: 'Reshape') with input shapes: [2048,11], [3] and with input tensors computed as partial shapes: input[1] = [?,128,7].
```

I can successfully run NCBI-disease dataset. So is it because of the different labels?
Any idea why this is happening and how I can fix it? Any help is highly appreciated!

**Comment by gccome** [comment]
In the paper you also experimented on i2b2 2010 dataset, but only for disease entity. Does it mean we cannot modify the label convention in the code and we can only work with one type of entity?

**Comment by wonjininfo** [comment]
Hi, 
You need to replace number 7 with [ the number of labels +1 (for padding)] (which in this case, 11) in line no. 381, 446, 447, 448
Thanks, 
WonJin

**Comment by gccome** [comment]
Hi @wonjininfo thanks for your reply. Let me try it and get back to you:)

**Comment by gccome** [comment]
Thanks @wonjininfo the program is running now. I will report here once I have results on those three entity types!

**Comment by gccome** [comment]
Hi @wonjininfo the running finished successfully, and it generated token_test.txt and label_test.txt. However, when I run ner_detokenizer.py, the following error occured:
```
133113 152657
Error! : len(ans['labels']) != len(bert_pred['labels']) : Please report us
Traceback (most recent call last):
  File "biocodes/ner_detokenize.py", line 88, in <module>
    detokenize(args.answer_path, args.token_test_path, args.label_test_path, args.output_dir)
  File "biocodes/ner_detokenize.py", line 77, in detokenize
    raise
```

**Comment by gccome** [comment]
Hi @wonjininfo , I think I might found where the issue is. In my dataset, some time-related tokens are not tokenized corrected after using wordpiece tokenizer. For example, "9/7/1992" is tokenzied as "9", "/", "7", "/", "1992" without adding "##". The correct subwords should be "##9", "##/", "##7", "##/", "##1992". Any idea how I could fix it? Thanks!

**Comment by zenanz** [comment]
I encountered the same issue when running `ner_detokenizer.py`. Apart from what @gccome mentioned, I also found that some tokens in the test.tsv are missing in token_test.txt.

**Comment by wonjininfo** [comment]
Hi,
We are about to release an update which contains hotfix for occasional missing token problem and new feature (which is mentioned on issue #13 ; output of probability).
I'm on reviewing the code and will notify of release in here.

Also, @gccome @zenanz  would you let us know a error inducing command line code so that we can reproduce the problem?
Missing token problem which we were aware of was occasional missing of only 1 token. 
Thanks!

**Comment by wonjininfo** [comment]
One more thing we need to tell you is that you need to modify `ner_detokenizer.py` to use BioBERT-NER for multi-label classification. 
Released version of `ner_detokenizer.py` only supports detokenization of single-label tasks. 
B, I, O tokens will be replaced with B-MISC, I-MISC or O but `ner_detokenizer` will make errors for other type of tokens like B-test, I-test, B-problem or B-treatment.
Thank you

**Comment by gccome** [comment]
Hi @wonjininfo really look forward to the new release!
Here is the command line I am using:
```
#!/usr/bin/env bash
BIOBERT_DIR=./pretrained_weights/biobert_pubmed_pmc
NER_DIR=./data/i2b2_2010/
OUTPUT=./output/i2b2_2010/
nohup python run_ner.py \
    --do_train=true \
    --do_eval=true \
    --do_test=true \
    --vocab_file=$BIOBERT_DIR/vocab.txt \
    --bert_config_file=$BIOBERT_DIR/bert_config.json \
    --init_checkpoint=$BIOBERT_DIR/biobert_model.ckpt \
    --train_batch_size=16 \
    --num_train_epochs=10.0 \
    --max_seq_length=128 \
    --num_labels=11 \
    --data_dir=$NER_DIR/ \
    --output_dir=$OUTPUT &> log/biobert_ner_i2b2_2010_20190227.txt &
```
I added `num_labels` as another argument.

And please see my previous reply below. My issue is at tokenization level, `BasicTokenizer` will tokenize my tokens first without adding `"##"`. Later in `ner_detokenizer.py`, those tokenized word piece will not be appended together to form the original token. Any ideas how I could fix this?
> Hi @wonjininfo , I think I might find where the issue is. In my dataset, some time-related tokens are not tokenized correctly after using `FullTokenizer`. For example, `"9/7/1992"` is tokenzied as `"9", "/", "7", "/", "1992"` without adding `"##"`, because the token runs through `BasicTokenizer` first. Any idea how I could fix it?
> 
> I am thinking since `FullTokenizer` pass through `BasicTokenizer` first, should I pass all the original tokens through `BasicTokenizer` and reconstruct the dataset?

**Comment by zenanz** [comment]
> Hi,
> We are about to release an update which contains hotfix for occasional missing token problem and new feature (which is mentioned on issue #13 ; output of probability).
> I'm on reviewing the code and will notify of release in here.
> 
> Also, @gccome @zenanz would you let us know a error inducing command line code so that we can reproduce the problem?
> Missing token problem which we were aware of was occasional missing of only 1 token.
> Thanks!

Thank you so much @wonjininfo ! The script I am using and the error reported in command lines are similar to what @gccome reported. However, I found that there are sometimes more than 1 consecutive tokens missing in token_test.txt. For example.

```
-imidazol-4yl]carbonyl}-l-piperazinyl)-l-naphthoic	I-chemCompound
acid	I-chemCompound
;	O
and	O
pharmaceutically	O
acceptable	O
salts	O
thereof	O
.	O
```
Turns into
```
im O

thereof O
. O
```
So far I can't find any pattern in which this error occurs.

**Comment by kormilitzin** [comment]
Thank you @gccome and @wonjininfo, very helpful! I will amend my code and (fingers crossed) it will run.

**Comment by wonjininfo** [comment]
> Hi,
> We are about to release an update which contains hotfix for occasional missing token problem and new feature (which is mentioned on issue #13 ; output of probability).
> I'm on reviewing the code and will notify of release in here.
> 
> Also, @gccome @zenanz thank you for your error reporting. Would you let us know a error inducing command line code so that we can reproduce the problem?
> Missing token problem which we were aware of was occasional missing of only 1 token.
> Thanks!

We updated the repository recently.

There was a few problems regarding the number of tokens. We fixed one missing token problem(occasional missing of 1 token) at f8bdd2b. 

However, I checked other problems (such as the one @gccome and @zenanz mentioned) with @parao0628 , who majorly dealt with preprocessing of NER task datasets (also an author of this paper as well).

Datasets which we distributed with the codes, are processed by our own _preprocessing script_ which splits `9/7/1992` into 
```
9
/
7
/
1992
```
and `-imidazol-4yl]carbonyl}-l-piperazinyl)-l-naphthoic` into
```
-
imidazol
-
4yl
]
carbony
}
...
```
So I think you need to do the same steps for i2b2 dataset.

Unfortunately, we have no plans to make our preprocessing script public. However, you can find the alternative codes from **[`here`](https://github.com/spyysalo/standoff2conll)** which my colleague got inspired from.

**Comment by gccome** [comment]
Thanks @wonjininfo , preprocessing token makes sense to me. Look forward to the new release!

**Comment by Tomas0413** [comment]
@gccome I just found this closed issue as I'm facing the same problem as you reported:
```
Error! : len(ans['labels']) != len(bert_pred['labels']) : Please report us
```
As I understand preprocessing of the datasets should resolve this issue, but I'm curious if you managed to get it working for you with [standoff2conll](https://github.com/spyysalo/standoff2conll) or used some other tools?

**Comment by gccome** [comment]
No I have to preprocess the dataset.
