### ISSUE TITLE
Error when Running Biobert on a variety of biomedical corpora

### ISSUE THREAD

**Issue by JinweiZhu** [dmis-lab/biobert#147]
When I run Biobert Named Entity Recognition on the NCBI biomedical corpora out of all the biomedical corpora listed here [https://github.com/BaderLab/Biomedical-Corpora](url)(everything is in tsv), I have an error in which the system does not seem to recognize "B-DISO". Here is the feedback of my error:  Traceback (most recent call last):
  File "run_ner.py", line 651, in <module>
    tf.app.run()
  File "/home/jz3395/.local/lib/python2.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/jz3395/.local/lib/python2.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/jz3395/.local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_ner.py", line 540, in main
    train_examples, label_list, FLAGS.max_seq_length, tokenizer, train_file)
  File "run_ner.py", line 297, in filed_based_convert_examples_to_features
    feature = convert_single_example(ex_index, example, label_list, max_seq_length, tokenizer,mode)
  File "run_ner.py", line 247, in convert_single_example
    label_ids.append(label_map[labels[i]])
KeyError: u'B-DISO'

Here everything in the NCBi corpora is either marked as O, B-DISO, and I-DISO. Is there any other differently annotated corpora that you would recommend me to try on? Would u pls send me the link? Or can u tell me what's the problem of my annotated corpora and hence how I can solve the problem?

**Comment by wonjininfo** [comment]
Hi JinweiZhu,
Would you replace B-DISO, I-DISO to B and I respectively, and rerun run_ner.py?
Our code specifies labels as follows. 
https://github.com/dmis-lab/biobert/blob/37599fb978e3b584a6e9aa9abca1f38588bfff4f/run_ner.py#L191-L192
Where "X" stands for sub-word tokens (such as ##word).
Thanks!
