### ISSUE TITLE
error :replicating biobert exactly with NCbI dataset 

### ISSUE THREAD

**Issue by ayodejioogunseye** [dmis-lab/biobert#190]
Hello, pls i tried to replicate  the  trainig as specified  aand using same NCIB dataset buut got stalked  here .

this code line"
$ python run_ner.py --do_train=true --do_eval=true --vocab_file=$BIOBERT_DIR/vocab.txt --bert_config_file=$BIOBERT_DIR/bert_config.json --init_checkpoint=$BIOBERT_DIR/model.ckpt-1000000 --num_train_epochs=10.0 --data_dir=$NER_DIR --output_dir=$OUTPUT_DIr "

(tf15) C:\Users\Ayodee\biobert>python run_ner.py --do_train=true --do_eval=true --vocab_file$BIOBERT_DIR/vocab.txt --bert_config_file=BIOBERT_DIR/bert_config.json --init_checkpoint=BIOBERT_DIR/model.ckpt-1000000 --num_train_epochs=10.0 --data_dir=NER_DIR --output_dir=OUTPUT_DIR
WARNING:tensorflow:From C:\Users\Ayodee\biobert\optimization.py:87: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\flags\_validators.py:206: UserWarning: Flag --task_name has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
WARNING:tensorflow:From run_ner.py:651: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

Traceback (most recent call last):
  File "run_ner.py", line 651, in <module>
    tf.app.run()
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\app.py", line 306, in run
    flags_parser,
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\app.py", line 375, in _run_init
    flags_parser=flags_parser,
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\app.py", line 220, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\tensorflow_core\python\platform\app.py", line 31, in _parse_flags_tolerate_undef
    return flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\tensorflow_core\python\platform\flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\flags\_flagvalues.py", line 673, in __call__
    self.validate_all_flags()
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\flags\_flagvalues.py", line 533, in validate_all_flags
    self._assert_validators(all_validators)
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\flags\_flagvalues.py", line 568, in _assert_validators
    raise _exceptions.IllegalFlagValueError('\n'.join(messages))
absl.flags._exceptions.IllegalFlagValueError: flag --vocab_file=None: Flag --vocab_file must have a value other than None.

**Comment by ayodejioogunseye** [comment]
used tenforflow 1.15.2  as  per instruction in requirement.txt  
 WARNING:tensorflow:From C:\Users\Ayodee\biobert\optimization.py:87: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\flags\_validators.py:206: UserWarning: Flag --task_name has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
WARNING:tensorflow:From C:\Users\Ayodee\biobert\run_ner.py:651: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From C:\Users\Ayodee\biobert\run_ner.py:466: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0724 16:58:51.533188 12640 module_wrapper.py:139] From C:\Users\Ayodee\biobert\run_ner.py:466: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From C:\Users\Ayodee\biobert\run_ner.py:466: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0724 16:58:51.534185 12640 module_wrapper.py:139] From C:\Users\Ayodee\biobert\run_ner.py:466: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From C:\Users\Ayodee\biobert\modeling.py:92: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0724 16:58:51.534185 12640 module_wrapper.py:139] From C:\Users\Ayodee\biobert\modeling.py:92: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Traceback (most recent call last):
  File "C:\Users\Ayodee\biobert\run_ner.py", line 651, in <module>
    tf.app.run()
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Ayodee\biobert\run_ner.py", line 473, in main
    bert_config = modeling.BertConfig.from_json_file(FLAGS.bert_config_file)
  File "C:\Users\Ayodee\biobert\modeling.py", line 93, in from_json_file
    text = reader.read()
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\Ayodee\anaconda3\envs\tf15\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: BIOBERT_DIR/bert_config.json : The system cannot find the path specified.

; No such process
